project_id = "ohfkcxwwvksrjymkgloo"

[functions.track-blog-view]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.admin-data-access]
verify_jwt = true

[functions.admin-orders-access]
verify_jwt = true

[functions.create-order]
verify_jwt = false

[functions.update-exchange-rates]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.send-customer-email]
verify_jwt = false

[functions.submit-kyc]
verify_jwt = false

[functions.admin-kyc-access]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.check-email-domain]
verify_jwt = true
