project_id = "ohfkcxwwvksrjymkgloo"

[functions.track-blog-view]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.admin-data-access]
verify_jwt = true

[functions.admin-orders-access]
verify_jwt = true

[functions.create-order]
verify_jwt = false

[functions.update-exchange-rates]
verify_jwt = false