/**
 * Regenerates public/_redirects and validates every redirect surface so they
 * always match the active domain configuration.
 *
 * Runs automatically before `vite dev` and `vite build` via the predev /
 * prebuild npm hooks (see package.json).
 *
 * Guarantees:
 *   1. public/_redirects is written from the single config below.
 *   2. The only cross-domain rules are OLD_DOMAINS -> PRIMARY_DOMAIN (301).
 *   3. No stale branding slug (alperrefrigas) survives as a *target* anywhere,
 *      and no other redirect surface (netlify.toml, public/.htaccess) points at
 *      a stale domain.
 *
 * Domain source of truth (first match wins):
 *   1. SITE_URL env var (build secret / CI override)
 *   2. VITE_SITE_URL from .env
 *   3. DEFAULT_SITE_URL below
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { resolve } from "path";

const DEFAULT_SITE_URL = "https://alperrefrigerants.com";

/** Legacy domains that must 301 to the primary domain. */
const OLD_DOMAINS = ["alperrefrigas.com"];

/** Branding slugs that must never appear as a redirect target. */
const STALE_BRANDING = ["alperrefrigas"];

/** Path-level redirects (SEO consolidation + legacy URLs). */
const PATH_REDIRECTS: Array<[from: string, to: string]> = [
  ["/products/air-conditioners", "/products/accessories"],
  ["/freon-wholesale", "/products"],
  ["/shipping", "/shipping-policy"],
  ["/products.html", "/products"],
  ["/about.html", "/about"],
  ["/contact.html", "/contact"],
  ["/home", "/"],
  ["/index", "/"],
  ["/index.html", "/"],
];

function loadEnvFile(): Record<string, string> {
  const path = resolve(".env");
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (match) out[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

const env = { ...loadEnvFile(), ...process.env } as Record<string, string>;
const BASE_URL = (env.SITE_URL || env.VITE_SITE_URL || DEFAULT_SITE_URL).replace(/\/+$/, "");
const PRIMARY_DOMAIN = BASE_URL.replace(/^https?:\/\//, "");

function renderRedirects(): string {
  const canonical = [
    `http://www.${PRIMARY_DOMAIN}/* ${BASE_URL}/:splat 301!`,
    `https://www.${PRIMARY_DOMAIN}/* ${BASE_URL}/:splat 301!`,
    `http://${PRIMARY_DOMAIN}/* ${BASE_URL}/:splat 301!`,
  ];

  const legacy = OLD_DOMAINS.flatMap((domain) => [
    `http://${domain}/* ${BASE_URL}/:splat 301!`,
    `https://${domain}/* ${BASE_URL}/:splat 301!`,
    `http://www.${domain}/* ${BASE_URL}/:splat 301!`,
    `https://www.${domain}/* ${BASE_URL}/:splat 301!`,
  ]);

  const paths = PATH_REDIRECTS.map(([from, to]) => `${from} ${to} 301!`);

  return [
    "# GENERATED FILE - do not edit by hand.",
    "# Regenerated by scripts/generate-redirects.ts on every dev/build.",
    "",
    `# Force HTTPS and non-www (primary host: ${BASE_URL})`,
    ...canonical,
    "",
    "# Legacy domain -> new primary domain",
    ...legacy,
    "",
    "# Path-level redirects",
    ...paths,
    "",
    "# Handle SPA routing",
    "/*    /index.html   200",
    "",
    "# Remove trailing slashes",
    "/*/ /:splat 301!",
    "",
  ].join("\n");
}

interface Problem {
  file: string;
  message: string;
}

function validate(redirects: string): Problem[] {
  const problems: Problem[] = [];

  // 1. Every cross-domain target must be the primary domain.
  redirects.split("\n").forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const [, target] = trimmed.split(/\s+/);
    if (!target) return;
    const match = target.match(/^https?:\/\/([^/]+)/);
    if (match && match[1] !== PRIMARY_DOMAIN) {
      problems.push({
        file: "public/_redirects",
        message: `redirect target "${target}" is not the primary domain (${PRIMARY_DOMAIN})`,
      });
    }
    if (match && STALE_BRANDING.some((slug) => target.includes(slug))) {
      problems.push({
        file: "public/_redirects",
        message: `stale branding slug in redirect target "${target}"`,
      });
    }
  });

  // 2. Old domains must each have a 301 to the primary domain.
  OLD_DOMAINS.forEach((domain) => {
    if (!redirects.includes(`https://${domain}/* ${BASE_URL}/:splat 301!`)) {
      problems.push({
        file: "public/_redirects",
        message: `missing 301 mapping for legacy domain ${domain}`,
      });
    }
  });

  // 3. Other redirect surfaces must not reference a stale domain.
  ["netlify.toml", "public/.htaccess"].forEach((file) => {
    const path = resolve(file);
    if (!existsSync(path)) return;
    const contents = readFileSync(path, "utf8");
    STALE_BRANDING.forEach((slug) => {
      contents.split("\n").forEach((line, index) => {
        if (line.includes(slug)) {
          problems.push({ file, message: `stale branding "${slug}" on line ${index + 1}` });
        }
      });
    });
  });

  // 4. Absolute links in the app must use the primary domain and must not
  //    point at a path that is itself a redirect source.
  const redirectSources = new Set(PATH_REDIRECTS.map(([from]) => from));
  const linkPattern = /https?:\/\/([a-z0-9.-]*alperrefrig[a-z0-9.-]*)((?:\/[^\s"'`)<>\\]*)?)/gi;

  auditFiles().forEach((file) => {
    const contents = readFileSync(resolve(file), "utf8");
    contents.split("\n").forEach((line, index) => {
      for (const match of line.matchAll(linkPattern)) {
        const [, host, path = ""] = match;
        if (host !== PRIMARY_DOMAIN && !host.endsWith(`.${PRIMARY_DOMAIN}`)) {
          problems.push({
            file,
            message: `line ${index + 1}: absolute link uses "${host}" instead of ${PRIMARY_DOMAIN}`,
          });
        }
        const cleanPath = path.replace(/[.,;)]+$/, "");
        if (redirectSources.has(cleanPath)) {
          problems.push({
            file,
            message: `line ${index + 1}: link points at "${cleanPath}", which 301-redirects to "${
              PATH_REDIRECTS.find(([from]) => from === cleanPath)?.[1]
            }"`,
          });
        }
      }
    });
  });

  return problems;
}

/** Files that may contain absolute site links. */
function auditFiles(): string[] {
  const roots = ["index.html", "src", "supabase/functions"];
  const exts = [".ts", ".tsx", ".html", ".json", ".txt"];
  const out: string[] = [];

  const walk = (rel: string) => {
    const abs = resolve(rel);
    if (!existsSync(abs)) return;
    if (statSync(abs).isDirectory()) {
      readdirSync(abs).forEach((child) => walk(`${rel}/${child}`));
      return;
    }
    if (exts.some((ext) => rel.endsWith(ext))) out.push(rel);
  };

  roots.forEach(walk);
  return out;
}

function main() {
  const redirects = renderRedirects();
  writeFileSync(resolve("public/_redirects"), redirects);

  const problems = validate(redirects);
  if (problems.length) {
    console.error("redirect validation failed:");
    problems.forEach((p) => console.error(`  - [${p.file}] ${p.message}`));
    process.exit(1);
  }

  console.log(
    `_redirects written for ${BASE_URL} (${OLD_DOMAINS.length} legacy domain(s), ${PATH_REDIRECTS.length} path rules) - validation passed`,
  );
}

main();
