INSERT INTO public.products (
  name,
  description,
  price,
  product_type,
  category,
  brand,
  availability,
  stock_quantity,
  sku,
  q20_units,
  q40_units,
  base_unit_price,
  mid_bulk_uplift_percent,
  custom_uplift_5_19,
  custom_uplift_20_39,
  custom_uplift_40_half,
  google_product_category,
  weight_kg,
  images
) VALUES (
  'Pioneer 12000 BTU Ductless Mini-Split',
  'High-efficiency ductless mini-split air conditioner with inverter technology. 12000 BTU cooling capacity, 19 SEER rating, WiFi enabled.',
  899.00,
  'air_conditioner',
  'mini-splits',
  'Pioneer',
  'in_stock',
  50,
  'AC-PIONEER-12K',
  20,
  40,
  750.00,
  12,
  35,
  25,
  15,
  'Home & Garden > Heating, Ventilation & Air Conditioning > Air Conditioners',
  35.5,
  ARRAY['https://images.unsplash.com/photo-1631545806609-6578d5de03cf?w=800']
);