-- Add high-demand HVAC accessories with SEO-optimized content
INSERT INTO public.products (
  name, 
  description, 
  category, 
  brand, 
  price, 
  product_type, 
  sku, 
  stock_quantity, 
  availability, 
  condition,
  technical_specs,
  applications,
  images,
  packaging_options,
  epa_approved,
  chemical_formula,
  gtin,
  dimensions,
  shipping_weight
) VALUES 

-- Electronic Refrigerant Leak Detector - High demand, critical tool
(
  'Professional Electronic Refrigerant Leak Detector R410A R134A R22 R32 HVAC',
  'Advanced electronic refrigerant leak detector for HVAC professionals. Detects all halogenated refrigerants including R410A, R134A, R22, R32, R404A, R407C. Features audio/visual alarms, adjustable sensitivity, and long battery life. Essential tool for EPA compliance and system maintenance. Highly sensitive sensor detects leaks as small as 0.1 oz/year. Perfect for commercial HVAC, automotive AC, and residential air conditioning leak detection.',
  'accessories',
  'HVAC Pro Tools',
  299.99,
  'accessory',
  'HLD-2024-PRO',
  25,
  'in_stock',
  'new',
  '{"sensor_type": "heated diode", "sensitivity": "0.1 oz/year", "battery_life": "40+ hours", "detection_range": "all halogenated refrigerants", "response_time": "immediate", "operating_temp": "-10°F to 120°F", "warranty": "2 years", "certifications": ["EPA approved", "UL listed"]}',
  '["Commercial HVAC leak detection", "Residential AC leak detection", "Automotive AC service", "Industrial refrigeration", "EPA compliance testing", "Preventive maintenance", "System commissioning", "Retrofit installations"]',
  '["https://example.com/leak-detector-1.jpg", "https://example.com/leak-detector-2.jpg"]',
  '["Single Unit", "2-Pack Professional", "5-Pack Commercial"]',
  true,
  'N/A',
  '1234567890123',
  '{"length": "8.5 inches", "width": "2.2 inches", "height": "1.5 inches"}',
  '1.2 lbs'
),

-- Digital Vacuum Pump - Essential for proper system evacuation
(
  'Digital 2-Stage Vacuum Pump 6 CFM HVAC Refrigeration R410A R134A R22 AC',
  'Professional 2-stage digital vacuum pump designed for HVAC and refrigeration systems. 6 CFM capacity with deep vacuum capability down to 15 microns. Built-in digital vacuum gauge with backlit display. Oil drain valve and sight glass for easy maintenance. Ideal for R410A, R134A, R22, R32 systems. Features anti-suckback valve and gas ballast for moisture removal. Essential for proper system evacuation and EPA compliance.',
  'accessories',
  'HVAC Pro Tools',
  449.99,
  'accessory',
  'DVP-6CFM-2024',
  15,
  'in_stock',
  'new',
  '{"capacity": "6 CFM", "stages": "2-stage rotary vane", "ultimate_vacuum": "15 microns", "motor": "1/2 HP", "oil_capacity": "20 oz", "inlet_size": "1/4 inch and 3/8 inch", "voltage": "115V/60Hz", "weight": "42 lbs", "warranty": "3 years"}',
  '["HVAC system evacuation", "Refrigeration service", "Air conditioning installation", "Heat pump service", "Commercial refrigeration", "Automotive AC service", "System dehydration", "Micron testing"]',
  '["https://example.com/vacuum-pump-1.jpg", "https://example.com/vacuum-pump-2.jpg"]',
  '["Single Unit", "2-Pack Commercial"]',
  true,
  'N/A',
  '2345678901234',
  '{"length": "18 inches", "width": "12 inches", "height": "14 inches"}',
  '45 lbs'
),

-- Refrigerant Recovery Machine - High demand for EPA compliance
(
  'Professional Refrigerant Recovery Machine R410A R134A R22 R32 EPA Compliant',
  'EPA-certified refrigerant recovery machine for safe and efficient refrigerant reclaim. Handles R410A, R134A, R22, R32, R404A, R407C, and R507A. Self-purging design prevents cross-contamination. Built-in scale and digital display for accurate refrigerant measurement. Meets EPA Section 608 requirements. High-capacity compressor with automatic shut-off. Essential for HVAC technicians and commercial service providers.',
  'accessories',
  'HVAC Pro Tools',
  1299.99,
  'accessory',
  'RRM-PRO-2024',
  8,
  'in_stock',
  'new',
  '{"recovery_rate": "2.5 lbs/min", "tank_capacity": "50 lbs", "refrigerants": ["R410A", "R134A", "R22", "R32", "R404A", "R407C", "R507A"], "compressor": "1/2 HP oil-less", "voltage": "115V/60Hz", "epa_certified": true, "weight": "85 lbs", "warranty": "5 years"}',
  '["Commercial HVAC service", "Residential AC service", "Automotive AC recovery", "Industrial refrigeration", "EPA compliance", "System decommissioning", "Refrigerant recycling", "Environmental protection"]',
  '["https://example.com/recovery-machine-1.jpg", "https://example.com/recovery-machine-2.jpg"]',
  '["Single Unit", "Commercial Package with Accessories"]',
  true,
  'N/A',
  '3456789012345',
  '{"length": "24 inches", "width": "18 inches", "height": "30 inches"}',
  '90 lbs'
),

-- Micron Gauge - Critical for vacuum testing
(
  'Digital Micron Gauge Vacuum Meter HVAC Refrigeration R410A System Testing',
  'Professional digital micron gauge for accurate vacuum measurement in HVAC systems. Measures from 50 to 9999 microns with 1 micron resolution. Large backlit LCD display with data logging capability. Essential for proper system evacuation verification and EPA compliance. Features automatic shut-off, low battery indicator, and temperature compensation. Includes carrying case and calibration certificate.',
  'accessories',
  'HVAC Pro Tools',
  189.99,
  'accessory',
  'DMG-PRO-2024',
  30,
  'in_stock',
  'new',
  '{"range": "50-9999 microns", "resolution": "1 micron", "accuracy": "±2% of reading", "display": "backlit LCD", "battery_life": "200+ hours", "operating_temp": "32°F to 120°F", "data_logging": true, "calibration": "NIST traceable", "warranty": "2 years"}',
  '["System evacuation testing", "Vacuum pump performance", "Leak testing verification", "EPA compliance testing", "Quality assurance", "System commissioning", "Troubleshooting", "Preventive maintenance"]',
  '["https://example.com/micron-gauge-1.jpg", "https://example.com/micron-gauge-2.jpg"]',
  '["Single Unit", "2-Pack Technician", "Calibration Kit Bundle"]',
  true,
  'N/A',
  '4567890123456',
  '{"length": "6 inches", "width": "3 inches", "height": "1.5 inches"}',
  '0.8 lbs'
),

-- Electronic Refrigerant Scale - High precision weighing
(
  'Electronic Refrigerant Charging Scale 220 lbs HVAC R410A R134A R22 Digital',
  'Professional electronic refrigerant charging scale with 220 lb capacity and 0.1 oz precision. Large backlit display with tare function and data hold. Refrigerant-resistant platform with removable tank hooks. Essential for accurate refrigerant charging and EPA compliance. Features auto-shutoff, low battery indicator, and temperature compensation. Includes carrying case and AC adapter.',
  'accessories',
  'HVAC Pro Tools',
  259.99,
  'accessory',
  'ERS-220-2024',
  20,
  'in_stock',
  'new',
  '{"capacity": "220 lbs", "precision": "0.1 oz", "platform_size": "12x12 inches", "display": "backlit LCD", "power": "AC adapter or 6 AA batteries", "tare_function": true, "data_hold": true, "temperature_compensation": true, "warranty": "3 years"}',
  '["Refrigerant charging", "System servicing", "EPA compliance", "Accurate measurements", "Commercial HVAC", "Residential AC service", "Automotive AC", "Quality control"]',
  '["https://example.com/scale-1.jpg", "https://example.com/scale-2.jpg"]',
  '["Single Unit", "2-Pack Commercial", "Professional Kit with Accessories"]',
  true,
  'N/A',
  '5678901234567',
  '{"length": "14 inches", "width": "12 inches", "height": "4 inches"}',
  '12 lbs'
),

-- Refrigerant Identifier - Safety and compliance tool
(
  'Refrigerant Identifier Analyzer R410A R134A R22 R32 HVAC EPA Compliant Tool',
  'Professional refrigerant identifier for accurate refrigerant analysis and contamination detection. Identifies over 50 refrigerants including R410A, R134A, R22, R32, R404A, R407C. Detects contamination, moisture, and non-condensables. Essential for EPA compliance and safety. Fast 30-second analysis with digital display and printer output. Prevents equipment damage from contaminated refrigerants.',
  'accessories',
  'HVAC Pro Tools',
  2499.99,
  'accessory',
  'RID-PRO-2024',
  5,
  'in_stock',
  'new',
  '{"refrigerants_detected": "50+", "analysis_time": "30 seconds", "contamination_detection": true, "moisture_detection": true, "printer": "built-in thermal printer", "display": "color LCD", "database": "updatable", "epa_approved": true, "warranty": "3 years"}',
  '["Refrigerant analysis", "Contamination detection", "EPA compliance", "Safety verification", "Commercial HVAC", "Industrial refrigeration", "Recovery operations", "Quality assurance"]',
  '["https://example.com/identifier-1.jpg", "https://example.com/identifier-2.jpg"]',
  '["Single Unit", "Commercial Package with Printer Paper"]',
  true,
  'N/A',
  '6789012345678',
  '{"length": "12 inches", "width": "8 inches", "height": "6 inches"}',
  '15 lbs'
);